language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements_dev.txt
script:
  - nosetests --with-coverage --cover-package borax
  - flake8 borax tests --ignore=E501 --max-complexity 10
  - coverage